### ISSUE TITLE
[質問] 分かち書き器について

### ISSUE THREAD

**Issue by CHaies** [hottolink/hottoSNS-w2v#1]
使わせていただいております．
質問なのですが，Twitterの分かち書きにのみMecabではなくJumanを使用している理由は何でしょうか？
またこの理由から，ツイートの分析時にこの分散表現を使用する場合，MecabではなくJumanを用いて分かち書きを行うほうが適切なのでしょうか？

**Comment by htl-tsakaki** [comment]
質問にご回答します。

> Twitterの分かち書きにのみMecabではなくJumanを使用している理由は何でしょうか？

Twitterの分かち書きについては，社内で予備実験において，Jumanにより分かち書き結果が一番良いスコアであったため，Jumanを採用しております．

> ツイートの分析時にこの分散表現を使用する場合，MecabではなくJumanを用いて分かち書きを行うほうが適切なのでしょうか？

それが最適だと考えています．ただ速度や実行環境上の制約からMeCab+ipadic-neologdで分かち書きしたとしても，実用上，大きな問題はないです．

参考までに社内予備実験の結果を掲載しておきます．

#### (参考)Twitterの分かち書きについて
* Twitterはくだけた文体が多いことから，通常の形態素解析器では分かち書きの性能が十分でないことが知られている
	* F値は，MeCab(IPADIC) = 90%前後，KyTea(BCCWJ+UniDic) = 92%程度 という報告がある[1,2]
	* KyTeaをTwitterコーパスで追加学習すると，95%程度まで向上させられる？[2]
	* Jumanは未知語モデルを搭載しているため，比較的頑健な処理ができるとされている[3]

	```
    [1] 北川善彬, 小町守. 深層ニューラルネットワークを利用した日本語単語分割.
	[2] 森信介. 多様なテキストの言語処理(招待講演). 第112回音声言語情報処理研究会 (SIG-SLP).  http://sig-slp.jp/2016-SLP-112.html
	[3] 笹野遼平, 黒橋禎夫, and 奥村学. "日本語形態素解析における未知語処理の一手法―既知語から派生した表記と未知オノマトペの処理―." 自然言語処理 21.6 (2014): 1183-1205.
	```

* このため，Twitterの分かち書き精度向上を目的として構築されたコーパス(Twitter Corpus)が存在する
    * 約1,000文の分かち書き・品詞付与を行ったデータセット

    ```
    大崎彩葉, 唐口翔平, 大迫拓矢, 佐々木俊哉, 北川善彬, 堺澤勇也, 小町守. Twitter 日本語形態素解析のためのコーパス構築.
    https://github.com/tmu-nlp/TwitterCorpus
	```
	
* そこで，実際にTwitterの本文を分かち書きを行い，いずれの方法が優れているかを簡単にテストした
	* 対象文 : 129文をランダム抽出
	* 形態素解析器および辞書・モデル : 以下の5種類
		1. MeCab + IPADIC
		2. MeCab + [mecab-ipadic-NEologd](https://github.com/neologd/mecab-ipadic-neologd)
		3. Juman
		4. KyTea + default(BCCWJ+UniDic)
		5. KyTea + Twitter Corpus(re-training)
	* 評価方法 : 文ごとに，分かち書き誤りが特に少ない方法に投票(複数投票可)
* 得票結果は以下のとおり．今次のテストでは，Jumanが最良という結果になった

	| Tokenizer | Dict / Model          | 得票数 |
	|-----------|-----------------------|--------|
	| MeCab     | ipadic                | 37     |
	| MeCab     | mecab-ipadic-NEologd  | 41     |
	| Juman     | default               | 47     |
	| KyTea     | default(BCCWJ+UniDic) | 16     |
	| KyTea     | twitter               | 14     |

**Comment by CHaies** [comment]
予備実験に基づいていたんですね、謎が解けました！
即座のご返答ありがとうございます！
